version: '2'
services:
    web:
        image: bushrangers/alpine-caddy-v2
        ports:
            -   80:80
        volumes:
            -   ./Caddyfile:/etc/Caddyfile
            -   ./public:/var/www/html
            -   ./.caddy:/root/.caddy
