# Docker Hub CI/CD for Multi Arch Images...
name: buildx

on:

  #pull_request:
  #  branches:
  #    - master
  #push:
  #  branches:
  #    - master
  #  tags:

  # Allow for manual triggers of builds
  workflow_dispatch:

  # Schedule weekly cron to build image...
  schedule:
    - cron:  '0 0 * * 1'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: bushrangers/alpine-caddy-v2:tagname # Replace 'tagname' as needed
          build-args: |
            BUILD_DATE=${{ steps.date.outputs.date }}
            VERSION=1.0.0
            VCS_REF=${{ github.sha }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6

      - name: Logout of Docker Hub
        run: docker logout

      - name: Get the current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%SZ')"

      - name: Clear
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json


